### ISSUE TITLE
Support for `0x0f 0x84` (`je`) opcode

### ISSUE THREAD

**Issue by ktf** [igprof/igprof#54]
Looks like now we have the following preambles for the jemalloc version of `free` when running cmsRun:

```
0x00007ffff56841f0 <+0>:	48 85 ff	test   %rdi,%rdi
0x00007ffff56841f3 <+3>:	0f 84 e4 01 00 00	je     0x7ffff56843dd <free+493>
```

Not only we need to make sure the opcode is recognized, but we need to fix the relative short jump so that it's correct also when relocated in the trampoline.

This problem appears in the log as:

```
*** IgProf(10549, 1422215277.943): free (0x7f5518a1d1f0) + 0x3: unrecognised prologue (found 0xf 0x84 0xe4 0x1)
```

and seems to cause a bunch of errors of the kind:

```
*** IgProf(10224, 1422213918.736): new MEM_LIVE resource XXXXXX of YYYYYYY bytes was never freed in ZZZZZZZZ
```

because the profiler cannot keep track of deallocations.

**Comment by ktf** [comment]
@dpiparo @VinInn I think this accounts for both Atom issues and ROOT6 ones. Can you confirm you see:

```
* IgProf(10549, 1422215277.943): free (0x7f5518a1d1f0) + 0x3: unrecognised prologue (found 0xf 0x84 0xe4 0x1)
```

as well? Can you try running with cmsRunGlibC? @davidlt @degano did we change jemalloc at any point lately?

**Comment by davidlt** [comment]
Last update 9 months ago. You might want to check if GCC 4.8 and 4.9 generates the same code for `free()`.

**Comment by ktf** [comment]
Anyways #56 fixes the issue for me. Will deploy in CMSSW_7_4_X tomorrow.
